spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: breadOnLaptop
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update // validate fr checking the table structure
    show-sql: false